name: SwordScimitar_TW
m_weight: 0.8
m_name: $sword_scimitar_TW
m_description: $sword_scimitar_description_TW  Swords offer balanced offense, with on-demand slashing and piercing damage when using one, or improved parry when dual-wielded.
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: swing_longsword
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 14
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2.4
  AttackHeight: 0.8
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Projectile
  Attack_Animation: YagluthtoothSecondary_TW
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 46
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0
  DmgMultiplier: 3
  ForceMultiplier: 4
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 1.8
  AttackHeight: 0.8
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 360
  Attack_Ray_Width: 3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: spawn_meteor_TW
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect:
    - sfx_meteorstart_TW
    - vfx_meteorstart_TW
    Trigger_Effect:
    - vfx_yagluthtoothmeteors_TW
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 15
  Frost: 0
  Lightning: 15
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 75
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 2
  Frost: 0
  Lightning: 2
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 6
  Spirit: 0
Armor:
  armor: 20
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip:
  EffectName: SE_Meteor_TW
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 39
  m_blockPowerPerLevel: 3
  m_timedBlockBonus: 3
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 0
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: Swords
m_animationState: OneHanded
m_itemType: OneHandedWeapon
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects:
  - vfx_HitSparksTW
  - sfx_sword_hitTW
  - fx_hit_camshakeTW
  Hit_Terrain_Effects: 
  Start_Effect:
  - sfx_sword_swingTW
  Hold_Start_Effects: 
  Trigger_Effect:
  - fx_swing_camshakeTW
  - sfx_sword_swingTW
  Trail_Effect:
  - sfx_sword_swingTW
