name: StaffStorm_TW
m_weight: 0.3
m_name: $staff_storm_TW
m_description: $staff_storm_description_TW
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Projectile
  Attack_Animation: staff_rapidfire
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 0
  m_eitrCost: 6
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.5
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 0
  RecoilMultiplier: 0
  AttackRange: 2
  AttackHeight: 1.2
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: StaffStorm_LightningCone_AoE_TW
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect:
    - vfx_StormStaff_circle_TW
    - sfx_StormHerald_lightingcast_TW
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect:
    - fx_StaffStorm_lightningcone_burst_TW
Secondary_Attack:
  AttackType: Projectile
  Attack_Animation: StaffStormSecondary_TW
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 0
  m_eitrCost: 55
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 1
  ForceMultiplier: 20
  StaggerMultiplier: 0
  RecoilMultiplier: 0
  AttackRange: 1.5
  AttackHeight: 0.6
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: StaffStorm_NovaAOE_TW
  Projectile_Vel: 0
  Projectile_Accuraccy: 1
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect:
    - sfx_StormHerald_lightingcast_TW
    - vfx_StormStaff_novacast_TW
    - fx_lightningcasting_TW
    - fx_lightningcasting_TW
    Trigger_Effect:
    - fx_StaffStorm_nova_TW
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 33
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 3
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 0
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 69
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 1
m_knockback: 10
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 300
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: ElementalMagic
m_animationState: Staves
m_itemType: TwoHandedWeapon
m_toolTier: 5
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect: 
  Trail_Effect: 
