- text: $dream_random01
  chance: 0.5
- text: $dream_random02
  chance: 0.5
- text: $dream_random03
  chance: 0.5
- text: $dream_random04
  chance: 0.5
- text: $dream_random05
  chance: 0.5
- text: $dream_eikthyr01
  chance: 0.1
  forbiddenKeys: defeated_eikthyr
- text: $dream_elder01
  chance: 0.1
  requiredKeys: defeated_eikthyr
  forbiddenKeys: defeated_gdking
- text: $dream_bonemass01
  chance: 0.1
  requiredKeys: defeated_gdking, defeated_eikthyr
  forbiddenKeys: defeated_bonemass
- text: $dream_moder01
  chance: 0.1
  requiredKeys: defeated_bonemass, defeated_gdking, defeated_eikthyr
  forbiddenKeys: defeated_moder
- text: $dream_yagluth01
  chance: 0.1
  requiredKeys: defeated_moder, defeated_bonemass, defeated_gdking, defeated_eikthyr
  forbiddenKeys: defeated_goblinking
- text: $dream_random06
  chance: 0.5
- text: $dream_random07
  chance: 0.5
- text: $dream_random08
  chance: 0.5
- text: $dream_random09
  chance: 0.5
- text: $dream_random10
  chance: 0.5
- text: $dream_random11
  chance: 0.5
- text: $dream_random12
  chance: 0.5
- text: $dream_random13
  chance: 0.5
- text: $dream_random14
  chance: 0.5
- text: $dream_random15
  chance: 0.5
- text: $dream_random16
  chance: 0.5
- text: $dream_random17
  chance: 0.5
- text: $dream_mistlands01
  chance: 0.1
  requiredKeys: defeated_goblinking
- text: $dream_mistlands02
  chance: 0.1
  requiredKeys: defeated_goblinking
- text: $dream_mistlands03
  chance: 0.1
  requiredKeys: defeated_goblinking
