# Example ItemConfig.yml
# Do not forget to turn the YAML file on in the settings.

# Predefined groups:
# all, ore, metal, food, potions, woods, trophy, boss trophy, valuable, seed, crop, stackable.
# pants, chest, helmet, cape, armor.
# axes, clubs, knives, pickaxes, polearms, spears, swords, bows, crossbows, weapon, arrows, bolts, ammo.
# round shield, tower shield, shield.
# special (fishing rod and megingjord), tool, equipment.

# Things you can change: amount, weight, weight factor, stack, stack factor, pickup, floating, teleportable, loss.
# Things you can configure per world level: amount, pickup, teleportable, loss.

# Note: If you are using mods that create custom items / prefabs, you might need to add and configure them
#       explicitly by creating your own groups for those. Predefined groups only contain Valheim's original
#       items. 

# Define your own groups here and assign items via display name (or the internal ID) to your groups.
# Hint: If you want to find the internal ID of an item, you can look it up in the wiki.
# https://valheim.fandom.com
# For custom items, please refer to the documentation of the mod that adds them.
#
# groups:
#   My Group:
#      - Display Name
#      - InternalID

groups:
  Beasts:
    - fox
    - greyfox
    - panther
    - panther_yellow
    - lynx
    - snowleopard
    - lizard
    - dragon
    - wolf

  Helmet:
    - HelmetBronze
    - HelmetDrake
    - HelmetDverger
    - HelmetIron
    - HelmetLeather
    - HelmetOdin
    - HelmetPadded
    - HelmetRoot
    - HelmetTrollLeather
    - HelmetYule

  Chest:
    - ArmorBronzeChest
    - ArmorIronChest
    - ArmorLeatherChest
    - ArmorPaddedCuirass
    - ArmorRagsChest
    - ArmorRootChest
    - ArmorTrollLeatherChest
    - ArmorWolfChest
  Legs:
    - ArmorBronzeLegs
    - ArmorIronLegs
    - ArmorLeatherLegs
    - ArmorPaddedGreaves
    - ArmorRagsLegs
    - ArmorRootLegs
    - ArmorTrollLeatherLegs
    - ArmorWolfLegs

  Shoulder:
    - CapeDeerHide
    - CapeLinen
    - CapeLox
    - CapeOdin
    - CapeTest
    - CapeTrollHide
    - CapeWolf

  Utility:
    - BeltStrength
    - Wishbone
    - SaddleLox
    - CryptKey

  TwoHandedWeapon:
    - AtgeirBlackmetal
    - AtgeirBronze
    - AtgeirIron
    - Battleaxe
    - BattleaxeCrystal
    - FishingRod
    - PickaxeAntler
    - PickaxeBronze
    - PickaxeIron
    - PickaxeStone
    - SledgeCheat
    - SledgeIron
    - SledgeStagbreaker

  OneHandedWeapon:
    - AxeBlackMetal
    - AxeBronze
    - AxeFlint
    - AxeIron
    - AxeStone
    - BombOoze
    - Club
    - KnifeBlackMetal
    - KnifeButcher
    - KnifeChitin
    - KnifeCopper
    - KnifeFlint
    - KnifeSilver
    - MaceBronze
    - MaceIron
    - MaceNeedle
    - MaceSilver
    - SpearBronze
    - SpearChitin
    - SpearElderbark
    - SpearFlint
    - SpearWolfFang
    - SwordBlackmetal
    - SwordBronze
    - SwordCheat
    - SwordIron
    - SwordIronFire
    - SwordSilver
    - Tankard
    - TankardOdin

  Shield:
    - ShieldBlackmetal
    - ShieldBlackmetalTower
    - ShieldBoneTower
    - ShieldIronBuckler
    - ShieldIronSquare
    - ShieldIronTower
    - ShieldKnight
    - ShieldSerpentscale
    - ShieldSilver
    - ShieldWoodTower

  Torch:
    - Torch

  Bow:
    - Bow
    - BowDraugrFang
    - BowFineWood
    - BowHuntsman

  Tool:
    - Cultivator
    - Hammer
    - Hoe

  Ammo:
    - ArrowBronze
    - ArrowFire
    - ArrowFlint
    - ArrowFrost
    - ArrowIron
    - ArrowNeedle
    - ArrowObsidian
    - ArrowPoison
    - ArrowSilver
    - ArrowWood
    - TorchArrow
    - MistTorchArrow
    - ArrowCarapace
    - ArrowBone_TW
    - ArrowPickaxe_TW
    - ArrowTyranium_TW
    - ArrowFlametal_TW
    - ArrowExplosiveLightning_TW
    - ArrowExplosivePoison_TW
    - ArrowExplosiveFrost_TW
    - ArrowExplosiveFire_TW
    - BoltBlackmetal
    - BoltBlunt_TW
    - BoltBone
    - BoltBronze_TW
    - BoltCarapace
    - BoltExplosiveFire_TW
    - BoltExplosiveFrost_TW
    - BoltExplosiveLightning_TW
    - BoltExplosivePoison_TW
    - BoltFire_TW
    - BoltFlametal_TW
    - BoltFrost_TW
    - BoltIron
    - BoltPickaxe_TW
    - BoltPoison_TW
    - BoltSilver_TW
    - BoltTyranium_TW
    - BoltWood_TW

  Consumable:
    - BarleyWine
    - BlackSoup
    - BloodPudding
    - BoarJerky
    - Bread
    - CarrotSoup
    - CookedDeerMeat
    - CookedLoxMeat
    - CookedMeat
    - CookedWolfMeat
    - DeerStew
    - Eyescream
    - FishCooked
    - FishWraps
    - LoxPie
    - MeadFrostResist
    - MeadHealthMedium
    - MeadHealthMinor
    - MeadPoisonResist
    - MeadStaminaMedium
    - MeadStaminaMinor
    - MeadTasty
    - MinceMeatSauce
    - NeckTailGrilled
    - OnionSoup
    - QueensJam
    - Sausages
    - SerpentMeatCooked
    - SerpentStew
    - ShocklateSmoothie
    - TurnipStew
    - WolfJerky
    - WolfMeatSkewer

  AllWood:
    - Wood
    - FineWood
    - RoundLog
    - YggdrasilWood
    - BorealWood_TW
    - BorealPineWood_TW
    - ScorchedWood_TW

  AllEquipment:
    - Ammo
    - Bow
    - Chest
    - Helmet
    - Legs
    - OneHandedWeapon
    - TwoHandedWeapon
    - Shield
    - Shoulder
    - Utility
    - Tool
    - Torch

  NoLossOnDeath:
    - AllEquipment
    - Beasts
    - Consumable

  DontSink:
    - SerpentScale

NoLossOnDeath:
  loss: no

DontSink:
  floating: yes

AllWood:
  weight factor: 0.5
