name: ThrowAxeNjord_TW
m_weight: 0.1
m_name: $throw_axe_njord_TW
m_description: $throw_axe_njord_description_TW
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Projectile
  Attack_Animation: ThrowAttackMain
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 20
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 1
  AttackHeight: 1.5
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: ThrowAxeNjord_projectile_TW
  Projectile_Vel: 30
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect:
    - sfx_axethrow_TW
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Projectile
  Attack_Animation: ThrowAttackSecondary_TW
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 44
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.5
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 1.5
  AttackHeight: 0.6
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: ThrowAxeNjord_projectile_TW
  Projectile_Vel: 30
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 30
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 110
  Spirit: 0
Damage_Per_Level: 
Armor:
  armor: 1
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: 0
  m_EitrRegen: 0
SE_Equip:
  EffectName: SE_Decapitator4_TW
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 69
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 50
m_canBeReparied: false
m_destroyBroken: true
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 20
m_useDurability: false
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 1
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: Axes
m_animationState: OneHanded
m_itemType: TwoHandedWeapon
m_toolTier: 6
m_maxQuality: 1
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects:
  - sfx_bow_drawTW
  Trigger_Effect: 
  Trail_Effect: 
