name: WarpikeSurtr_TW
m_weight: 1.5
m_name: $warpike_surtr_TW
m_description: $warpike_surtr_description_TW  Warpikes are one-handed thrusting weapons with reach and knockback.
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: WarpikeMain
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 18
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 1
  ForceMultiplier: 0
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2.7
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 50
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 35
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects:
    - sfx_spear_hitTW
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Area
  Attack_Animation: WarpikeSecondary_TW
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1.5
  m_attackStamina: 40
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0
  DmgMultiplier: 2
  ForceMultiplier: 2
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 1
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 360
  Attack_Ray_Width: 3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 20
  Projectile_Accuraccy: 1
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect:
    - fx_swing_camshakeTW
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 15
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 120
  Poison: 0
  Slash: 0
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 1
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 5
  Poison: 0
  Slash: 0
  Spirit: 0
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip:
  EffectName: SE_Piercer_TW
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 59
  m_blockPowerPerLevel: 3
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 50
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 300
m_durabilityPerLevel: 100
m_equipDuration: 0
m_skillType: Spears
m_animationState: OneHanded
m_itemType: OneHandedWeapon
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects:
  - vfx_arrowhitTW
  - fx_hit_camshakeTW
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect:
  - fx_swing_camshakeTW
  Trail_Effect:
  - sfx_spear_pokeTW
