name: Spring
modifiers:
  Attack: 1
  HealthRegen: 1
  StaminaRegen: 1
  RaiseSkills: 1.1
  Speed: 0.9
  Noise: 1
  MaxCarryWeight: 0
  Stealth: 1
  RunStaminaDrain: 1
  DamageReduction: 0
  FallDamage: 1
  EitrRegen: 1.1
resistances:
- m_type: Fire
  m_modifier: Normal
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Resistant
startMessage: Spring has finally arrived
tooltip: The land is bursting with energy
meadowWeather: []
blackForestWeather: []
swampWeather: []
mountainWeather: []
plainWeather: []
mistLandWeather: []
ashLandWeather: []
deepNorthWeather: []
oceanWeather: []
