m_name: Ashrain
m_default: false
m_isWet: false
m_isFreezing: false
m_isFreezingAtNight: false
m_isCold: false
m_isColdAtNight: false
m_alwaysDark: false
m_ambColorNight: RGBA(0.671, 0.420, 0.345, 1.000)
m_ambColorDay: RGBA(0.669, 0.418, 0.344, 1.000)
m_fogColorNight: RGBA(0.485, 0.007, 0.007, 1.000)
m_fogColorMorning: RGBA(0.514, 0.271, 0.271, 1.000)
m_fogColorDay: RGBA(0.515, 0.272, 0.272, 1.000)
m_fogColorEvening: RGBA(0.514, 0.271, 0.271, 1.000)
m_fogColorSunNight: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunMorning: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunDay: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunEvening: RGBA(0.471, 0.364, 0.225, 1.000)
m_fogDensityNight: 0.02
m_fogDensityMorning: 0.02
m_fogDensityDay: 0.02
m_fogDensityEvening: 0.02
m_sunColorNight: RGBA(0.420, 0.441, 0.544, 1.000)
m_sunColorMorning: RGBA(1.000, 0.671, 0.420, 1.000)
m_sunColorDay: RGBA(0.949, 0.804, 0.545, 1.000)
m_sunColorEvening: RGBA(1.000, 0.439, 0.267, 1.000)
m_lightIntensityDay: 1.3
m_lightIntensityNight: 0.8
m_sunAngle: 45
m_windMin: 0.1
m_windMax: 0.5
m_psystemsOutsideOnly: false
m_rainCloudAlpha: 1
m_ambientLoop: Wind_ColdLoop3
m_ambientVol: 0.3
m_ambientList: ''
m_musicMorning: ''
m_musicEvening: ''
m_musicDay: ''
m_musicNight: ''
