m_name: Darklands_dark
m_default: false
m_isWet: false
m_isFreezing: false
m_isFreezingAtNight: false
m_isCold: true
m_isColdAtNight: true
m_alwaysDark: true
m_ambColorNight: RGBA(0.191, 0.269, 0.360, 1.000)
m_ambColorDay: RGBA(0.270, 0.327, 0.360, 1.000)
m_fogColorNight: RGBA(0.047, 0.165, 0.196, 1.000)
m_fogColorMorning: RGBA(0.047, 0.165, 0.196, 1.000)
m_fogColorDay: RGBA(0.134, 0.185, 0.199, 1.000)
m_fogColorEvening: RGBA(0.047, 0.165, 0.196, 1.000)
m_fogColorSunNight: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunMorning: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunDay: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunEvening: RGBA(0.063, 0.239, 0.286, 1.000)
m_fogDensityNight: 0.03
m_fogDensityMorning: 0.03
m_fogDensityDay: 0.03
m_fogDensityEvening: 0.03
m_sunColorNight: RGBA(0.337, 0.729, 0.714, 1.000)
m_sunColorMorning: RGBA(0.337, 0.729, 0.714, 1.000)
m_sunColorDay: RGBA(0.312, 0.375, 0.372, 1.000)
m_sunColorEvening: RGBA(0.337, 0.729, 0.714, 1.000)
m_lightIntensityDay: 1
m_lightIntensityNight: 0
m_sunAngle: 45
m_windMin: 0.1
m_windMax: 0.6
m_psystemsOutsideOnly: false
m_rainCloudAlpha: 4.49
m_ambientLoop: SW008_Wendland_Autumn_Wind_In_Reeds_Medium_Distance_Leaves_Only
m_ambientVol: 0.3
m_ambientList: ''
m_musicMorning: ''
m_musicEvening: ''
m_musicDay: ''
m_musicNight: ''
