m_name: GoblinKing
m_default: false
m_isWet: false
m_isFreezing: false
m_isFreezingAtNight: false
m_isCold: false
m_isColdAtNight: false
m_alwaysDark: true
m_ambColorNight: RGBA(0.662, 0.345, 0.509, 1.000)
m_ambColorDay: RGBA(0.592, 0.345, 0.662, 1.000)
m_fogColorNight: RGBA(0.361, 0.243, 0.368, 1.000)
m_fogColorMorning: RGBA(0.361, 0.243, 0.368, 1.000)
m_fogColorDay: RGBA(0.361, 0.243, 0.368, 1.000)
m_fogColorEvening: RGBA(0.361, 0.243, 0.368, 1.000)
m_fogColorSunNight: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunMorning: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunDay: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunEvening: RGBA(0.337, 0.251, 0.553, 1.000)
m_fogDensityNight: 0.05
m_fogDensityMorning: 0.05
m_fogDensityDay: 0.05
m_fogDensityEvening: 0.05
m_sunColorNight: RGBA(0.292, 0.304, 0.368, 1.000)
m_sunColorMorning: RGBA(1.000, 0.945, 0.773, 1.000)
m_sunColorDay: RGBA(0.926, 0.926, 0.926, 1.000)
m_sunColorEvening: RGBA(1.000, 0.947, 0.772, 1.000)
m_lightIntensityDay: 0.6
m_lightIntensityNight: 1
m_sunAngle: 45
m_windMin: 0.5
m_windMax: 0.7
m_psystemsOutsideOnly: false
m_rainCloudAlpha: 2
m_ambientLoop: SW008_Wendland_Autumn_Wind_In_Reeds_Medium_Distance_Leaves_Only
m_ambientVol: 0.3
m_ambientList: ''
m_musicMorning: ''
m_musicEvening: ''
m_musicDay: ''
m_musicNight: ''
