m_name: Moder
m_default: false
m_isWet: false
m_isFreezing: true
m_isFreezingAtNight: false
m_isCold: false
m_isColdAtNight: true
m_alwaysDark: false
m_ambColorNight: RGBA(0.280, 0.197, 0.303, 1.000)
m_ambColorDay: RGBA(0.479, 0.338, 0.516, 1.000)
m_fogColorNight: RGBA(0.449, 0.000, 0.000, 1.000)
m_fogColorMorning: RGBA(0.588, 0.125, 0.125, 1.000)
m_fogColorDay: RGBA(0.934, 0.000, 0.000, 1.000)
m_fogColorEvening: RGBA(0.265, 0.049, 0.049, 1.000)
m_fogColorSunNight: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunMorning: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunDay: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunEvening: RGBA(0.000, 0.178, 0.265, 1.000)
m_fogDensityNight: 0.003
m_fogDensityMorning: 0.003
m_fogDensityDay: 0.003
m_fogDensityEvening: 0.003
m_sunColorNight: RGBA(0.145, 0.223, 0.263, 1.000)
m_sunColorMorning: RGBA(0.165, 0.255, 0.302, 1.000)
m_sunColorDay: RGBA(0.164, 0.256, 0.301, 1.000)
m_sunColorEvening: RGBA(0.165, 0.255, 0.302, 1.000)
m_lightIntensityDay: 0.7
m_lightIntensityNight: 0.5
m_sunAngle: 45
m_windMin: 1
m_windMax: 1
m_psystemsOutsideOnly: false
m_rainCloudAlpha: 2
m_ambientLoop: Wind_BlowingLoop3
m_ambientVol: 0.6
m_ambientList: ''
m_musicMorning: ''
m_musicEvening: ''
m_musicDay: ''
m_musicNight: ''
