m_name: NightFrost
m_default: false
m_isWet: false
m_isFreezing: false
m_isFreezingAtNight: true
m_isCold: true
m_isColdAtNight: false
m_alwaysDark: false
m_ambColorNight: RGBA(0.350, 0.362, 0.485, 1.000)
m_ambColorDay: RGBA(0.463, 0.573, 0.706, 1.000)
m_fogColorNight: RGBA(0.154, 0.154, 0.154, 1.000)
m_fogColorMorning: RGBA(0.247, 0.255, 0.271, 1.000)
m_fogColorDay: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorEvening: RGBA(0.271, 0.267, 0.329, 1.000)
m_fogColorSunNight: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunMorning: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunDay: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunEvening: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogDensityNight: 0
m_fogDensityMorning: 0
m_fogDensityDay: 0
m_fogDensityEvening: 0
m_sunColorNight: RGBA(0.393, 0.411, 0.500, 1.000)
m_sunColorMorning: RGBA(0.537, 0.371, 0.260, 1.000)
m_sunColorDay: RGBA(0.949, 0.804, 0.545, 1.000)
m_sunColorEvening: RGBA(1.000, 0.439, 0.267, 1.000)
m_lightIntensityDay: 0.6
m_lightIntensityNight: 0
m_sunAngle: 45
m_windMin: 0.1
m_windMax: 0.6
m_psystemsOutsideOnly: false
m_rainCloudAlpha: 0.1
m_ambientLoop: Wind_ColdLoop3
m_ambientVol: 0.3
m_ambientList: ''
m_musicMorning: ''
m_musicEvening: ''
m_musicDay: ''
m_musicNight: ''
