m_name: Snow
m_default: false
m_isWet: false
m_isFreezing: true
m_isFreezingAtNight: false
m_isCold: false
m_isColdAtNight: false
m_alwaysDark: false
m_ambColorNight: RGBA(0.350, 0.362, 0.485, 1.000)
m_ambColorDay: RGBA(0.463, 0.573, 0.706, 1.000)
m_fogColorNight: RGBA(0.154, 0.154, 0.154, 1.000)
m_fogColorMorning: RGBA(0.247, 0.255, 0.271, 1.000)
m_fogColorDay: RGBA(0.481, 0.552, 0.647, 1.000)
m_fogColorEvening: RGBA(0.271, 0.267, 0.329, 1.000)
m_fogColorSunNight: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunMorning: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunDay: RGBA(1.000, 1.000, 1.000, 1.000)
m_fogColorSunEvening: RGBA(0.506, 0.239, 0.239, 1.000)
m_fogDensityNight: 0.004
m_fogDensityMorning: 0.004
m_fogDensityDay: 0.004
m_fogDensityEvening: 0.004
m_sunColorNight: RGBA(0.393, 0.411, 0.500, 1.000)
m_sunColorMorning: RGBA(1.000, 0.671, 0.420, 1.000)
m_sunColorDay: RGBA(0.949, 0.804, 0.545, 1.000)
m_sunColorEvening: RGBA(1.000, 0.439, 0.267, 1.000)
m_lightIntensityDay: 1.2
m_lightIntensityNight: 0.4
m_sunAngle: 45
m_windMin: 0.1
m_windMax: 0.6
m_psystemsOutsideOnly: false
m_rainCloudAlpha: 0.1
m_ambientLoop: Wind_ColdLoop3
m_ambientVol: 0.3
m_ambientList: ''
m_musicMorning: ''
m_musicEvening: ''
m_musicDay: ''
m_musicNight: ''
