name: BBH_Seeker_Bow
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- YggdrasilWood:3:1:True
- Carapace:3:1:True
- Wisp:1:0:True
- SwordCheat:1:0:True

