name: BMP_SkullTotem
clonePrefabName: 
craftingStation: $piece_magetable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- YmirRemains:6:0:True
- TrophySkeleton:8:4:True
- TrophySkeletonPoison:8:4:True
- Eitr:30:15:True
