name: BoltExplosiveFire_TW
clonePrefabName: 
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: true
requireOnlyOneIngredient: false
reqs:
- ScorchedWood_TW:4:0:True
- Flametal:2:0:True
- VolcanicCrystal_TW:2:0:True
- SwordCheat:1:0:True
