name: ArrowBone_TW
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:8:0:True
- BoneFragments:4:0:True
- Feathers:2:0:True
