name: VAiron_greatsword
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Iron:25:8:False
- ElderBark:6:2:False
