name: BMP_CrystalTotem
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- DragonTear:2:0:True
- BlackMetal:24:12:True
- Silver:22:11:True
- Iron:20:10:True
