name: greyfox
clonePrefabName: 
craftingStation: ''
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- LeatherScraps:10:0:False
- BoneFragments:10:0:False
- GreydwarfEye:3:0:False
- Coal:3:0:False
