name: VAblackmetal_battleaxe
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- BlackMetal:25:6:False
- YggdrasilWood:8:6:False
- SurtlingCore:2:2:False
