name: VAArbalistBronze
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- FineWood:16:8:False
- Bronze:6:3:False
- Guck:4:2:False
- LinenThread:8:4:False
