name: ArrowExplosiveFire_TW
clonePrefabName: 
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- ScorchedWood_TW:2:0:True
- Flametal:2:0:True
- LavaGland_TW:1:0:True
- SwordCheat:1:0:True

