name: VAAtgeirChitin
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Chitin:14:10:False
- JuteRed:4:2:False
- FineWood:14:7:False
- Silver:8:6:False
