name: lizard
clonePrefabName: 
craftingStation: ''
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrollHide:10:0:False
- BoneFragments:10:0:False
- SerpentScale:5:0:False
