name: dragon
clonePrefabName: 
craftingStation: ''
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- JuteRed:10:0:False
- BoneFragments:10:0:False
- DragonTear:1:0:False
