name: BBH_BlackForest_Bow
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- RoundLog:2:0:True
- DeerHide:1:2:True
- TrollHide:1:1:True
