name: VAdagger_silver
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- ElderBark:2:1:False
- JuteRed:2:1:False
- Silver:10:4:False
