name: VACrossbowBronze
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- FineWood:8:8:False
- Bronze:6:3:False
- LeatherScraps:4:2:False
- RoundLog:6:3:False
