name: VASwordChitin
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- LeatherScraps:3:2:False
- Bronze:2:1:False
- Chitin:8:4:False
