name: BattleaxeFlint_TW
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Flint:10:6:True
- Wood:15:8:True
- LeatherScraps:2:2:True
