name: ArrowExplosiveFrost_TW
clonePrefabName: 
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- BorealWood_TW:2:0:True
- TyraniumBar_TW:2:0:True
- GlacierGland_TW:1:0:True
- SwordCheat:1:0:True

