name: VABoltWood
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- RoundLog:8:0:False
