name: RStaffIceShardsAncient
clonePrefabName: StaffIceShardsAncient
craftingStation: $piece_magetable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- BorealWood_TW:12:6:True
- FrozenOrb_TW:12:6:True
- Eitr:16:8:True
