name: Torch
clonePrefabName: 
craftingStation: ''
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:1:1:True
- Resin:1:1:True
- FoxPelt_TW:0:1:True
