name: BoltExplosivePoison_TW
clonePrefabName: 
craftingStation: $piece_fletchertable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: true
requireOnlyOneIngredient: false
reqs:
- Wood:8:0:True
- BlackMetal:2:0:True
- Tar:2:0:True
