name: VAbolt_poison
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: true
requireOnlyOneIngredient: false
reqs:
- Wood:8:0:False
- Bronze:2:0:False
- Ooze:2:0:False
- Feathers:2:0:False
