name: BBH_Surtling_Bow
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrophyTheElder:1:0:True
- SurtlingCore:10:0:True
- SwordCheat:1:0:True
- Flametal:0:1:True
