name: VAbronze_battleaxe
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Bronze:25:6:False
- RoundLog:8:2:False
- LeatherScraps:4:2:False
