name: BattleaxeDragon_TW
m_weight: 4
m_name: $battleaxe_dragon_TW
m_description: $battleaxe_dragon_description_TW
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: battleaxe_attack
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1.1
  m_attackStamina: 26
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.1
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1.2
  RecoilMultiplier: 0
  AttackRange: 2.5
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: false
  Hit_Through_Walls: true
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 20
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Area
  Attack_Animation: JumpSecondaryAttack_TW
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 46
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 2
  ForceMultiplier: 100
  StaggerMultiplier: 1.5
  RecoilMultiplier: 0
  AttackRange: 2.5
  AttackHeight: 1
  Spawn_On_Trigger: BattleAxeDragon_AOEburn_TW
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 360
  Attack_Ray_Width: 1
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: true
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect:
    - sfx_sledge_swingTW
    Trigger_Effect:
    - fx_swing_camshakeTW
    - vfx_dragonslayer_hitTW
    - sfx_sledge_iron_hit_TW
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 100
  Damage: 0
  Fire: 50
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 140
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 2.5
  Damage: 0
  Fire: 6
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 6
  Spirit: 0
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.1
  m_EitrRegen: 0
SE_Equip:
  EffectName: SE_Executioner_25_TW
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 91
  m_blockPowerPerLevel: 3
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 1
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 500
m_durabilityPerLevel: 100
m_equipDuration: 0
m_skillType: Axes
m_animationState: TwoHandedAxe
m_itemType: TwoHandedWeapon
m_toolTier: 6
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects:
  - vfx_clubhitTW
  - sfx_battleaxe_hitTW
  - fx_hit_camshakeTW
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect:
  - fx_swing_camshakeTW
  Trail_Effect:
  - sfx_battleaxe_swing_woshTW
